Import('rtconfig')
from building import *

comm = 'libcpu/' + rtconfig.ARCH
if (rtconfig.CPU == 'cortex-m4') or (rtconfig.CPU == 'cortex-m3'):
    comm = 'libcpu/cortexm'

cwd = GetCurrentDir()
src = Glob('*.c') + Glob(comm + '/*.c') + Glob(comm + '/*.S')

CPPPATH = [cwd, cwd + '/' + comm]

group = DefineGroup('gdb', src, depend = ['RT_USING_GDB'], CPPPATH = CPPPATH)

Return('group')
