import copy
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')


CPPPATH = [cwd]

group = DefineGroup('gdb', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
